# Generated by Django 6.1 on 2026-08-27 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banlists', '0001_initial'),
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('deck_type', models.CharField(blank=True, max_length=100)),
                ('format', models.CharField(choices=[('TCG', 'TCG'), ('OCG', 'OCG')], default='TCG', max_length=10)),
                ('is_public', models.BooleanField(default=False)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='deck_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ban_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decks', to='banlists.banlist')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('section', models.CharField(choices=[('MAIN', 'Main Deck'), ('EXTRA', 'Extra Deck'), ('SIDE', 'Side Deck')], default='MAIN', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_cards', to='cards.card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_cards', to='decks.deck')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('deck', 'card', 'section'), name='unique_card_per_deck_section')],
            },
        ),
    ]
