# Generated by Django 6.1 on 2026-08-27 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deckcard',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddConstraint(
            model_name='deckcard',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1), ('quantity__lte', 3)), name='deck_card_quantity_between_1_and_3'),
        ),
    ]
