# Generated by Django 6.1 on 2026-08-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_alter_deckcard_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='is_sample',
            field=models.BooleanField(db_index=True, default=False, help_text='System-owned deck imported from a local sample source.'),
        ),
        migrations.AddField(
            model_name='deck',
            name='sample_archetype',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deck',
            name='sample_source',
            field=models.CharField(blank=True, help_text='Stable relative .ydk source path used for idempotent imports.', max_length=255, null=True, unique=True),
        ),
    ]
