"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

IS_VERCEL = bool(os.environ.get("VERCEL"))


def env_flag(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


# Keep the development key for local coursework use only. Production must
# provide a unique value through Vercel's encrypted environment variables.
DEVELOPMENT_SECRET_KEY = (
    "django-insecure-=)+ssnzsa56j7h8kvm$$=6@3^zg+c@3jh_n5g8mgs*51wsgu=3"
)
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", DEVELOPMENT_SECRET_KEY)
if IS_VERCEL and SECRET_KEY == DEVELOPMENT_SECRET_KEY:
    raise ImproperlyConfigured("DJANGO_SECRET_KEY must be set on Vercel.")

DEBUG = env_flag("DJANGO_DEBUG", default=not IS_VERCEL)

configured_hosts = os.environ.get("DJANGO_ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [
    host.strip() for host in configured_hosts.split(",") if host.strip()
]
if IS_VERCEL:
    ALLOWED_HOSTS.append(".vercel.app")

configured_csrf_origins = os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in configured_csrf_origins.split(",")
    if origin.strip()
]
if IS_VERCEL:
    CSRF_TRUSTED_ORIGINS.append("https://*.vercel.app")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tailwind',
    'theme',
    'cards',
    'decks',
    'collects',
    'banlists',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

database_url = os.environ.get("DATABASE_URL")
if database_url:
    parsed_database_url = urlparse(database_url)
    if parsed_database_url.scheme not in {"postgres", "postgresql"}:
        raise ImproperlyConfigured("DATABASE_URL must be a PostgreSQL URL.")

    database_options = {
        key: values[-1]
        for key, values in parse_qs(parsed_database_url.query).items()
        if values
    }
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": parsed_database_url.path.lstrip("/"),
            "USER": unquote(parsed_database_url.username or ""),
            "PASSWORD": unquote(parsed_database_url.password or ""),
            "HOST": parsed_database_url.hostname or "",
            "PORT": parsed_database_url.port or "",
            "OPTIONS": database_options,
            "CONN_MAX_AGE": 0,
            "CONN_HEALTH_CHECKS": True,
        }
    }
elif IS_VERCEL:
    raise ImproperlyConfigured(
        "DATABASE_URL must be set on Vercel; SQLite is not persistent there."
    )
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "yugioh-deck-builder-data",
        "TIMEOUT": 900,
        "OPTIONS": {"MAX_ENTRIES": 1000},
    }
}

DATA_CACHE_TIMEOUT = 900


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

# Course-project demo: accept any non-empty password. Password forms still
# require both confirmation fields to match.
AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Bangkok'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]
if IS_VERCEL:
    # Character-deck covers are bundled as deploy-time static assets. New
    # uploads need object storage and are intentionally not written locally.
    STATICFILES_DIRS.append(
        ("deck_covers", BASE_DIR / "media" / "deck_covers")
    )
SITE_AUDIO_ROOT = BASE_DIR / "static" / "audio"

# Tailwind CSS is compiled through the dedicated Django theme app. The
# existing handcrafted styles stay in static/css so the visual design can be
# migrated gradually without changing the current pages.
TAILWIND_APP_NAME = "theme"
NPM_BIN_PATH = "npm.cmd"


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# The local archive uses downloaded card images. Vercel uses the card CDN URLs
# already stored in the database so the 2+ GB image directory is not bundled.
USE_REMOTE_CARD_IMAGES = IS_VERCEL
SERVE_DECK_COVERS_AS_STATIC = IS_VERCEL

if IS_VERCEL:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 3600
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/login/'
