# Generated by Django 6.1 on 2026-08-27 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('format', models.CharField(choices=[('TCG', 'TCG'), ('OCG', 'OCG')], max_length=10)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BanListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('FORBIDDEN', 'Forbidden'), ('LIMITED', 'Limited'), ('SEMI_LIMITED', 'Semi-Limited')], max_length=30)),
                ('max_copies', models.PositiveSmallIntegerField(default=3)),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ban_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='banlists.banlist')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banlist_entries', to='cards.card')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ban_list', 'card'), name='unique_card_per_banlist')],
            },
        ),
    ]
