# Generated by Django 6.1 on 2026-08-27 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banlists', '0001_initial'),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banlistentry',
            name='max_copies',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddConstraint(
            model_name='banlistentry',
            constraint=models.CheckConstraint(condition=models.Q(('max_copies__gte', 0), ('max_copies__lte', 3)), name='banlist_max_copies_between_0_and_3'),
        ),
    ]
