# Generated by Django 6.1 on 2026-08-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banlists', '0002_alter_banlistentry_max_copies_and_more'),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='banlistentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('max_copies', 0), ('status', 'FORBIDDEN')), models.Q(('max_copies', 1), ('status', 'LIMITED')), models.Q(('max_copies', 2), ('status', 'SEMI_LIMITED')), _connector='OR'), name='banlist_status_matches_copy_limit'),
        ),
    ]
