# Generated by Django 6.1 on 2026-08-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('card_type', models.CharField(max_length=100)),
                ('frame_type', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('race', models.CharField(blank=True, max_length=100)),
                ('attribute', models.CharField(blank=True, max_length=50)),
                ('archetype', models.CharField(blank=True, max_length=255)),
                ('atk', models.IntegerField(blank=True, null=True)),
                ('defense', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('image_url_small', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
