# Generated by Django 6.1 on 2026-08-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='description_th',
            field=models.TextField(blank=True, help_text='Cached automatic Thai translation of the card text.'),
        ),
    ]
